# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
language: R
cache: packages

# enable remotes
r_github_packages:
- TomKellyGenetics/plot.igraph
- TomKellyGenetics/info.centrality
- TomKellyGenetics/graphsim
- TomKellyGenetics/pathway.structure.permutation

USE_RTOOLS: true

